### ISSUE TITLE
Umgang mit legacy Problemen

### ISSUE THREAD

**Issue by DataCerealz** [irgroup-classrooms/dis22-2022#15]
Nach Aufsetzen der Workflows haben wir einige Probleme in Bezug auf Einhalten von Standards aber auch Code Qualität generell (siehe Ergebnisse des lint-Workflows oder hier der "Security"-Tab mit den CodeQL Ergebnissen).
Wollen wir den bestehenden Code (bisher ist ja noch keiner von uns mit drin, nur das originale Repository) überhaupt fixen?
Oder generell ausschließlich unsere selbst geschriebenen Funktionen testen/qualitätssichern in Zukunft?

**Comment by DatenkrakeWasTaken** [comment]
Ich kann mich gerne um die legacy Probleme kümmern. Im Original-Code gabs bei Jannik und mir Probleme mit relativen Imports, das würde ich dann direkt für eine funktionierende Grundlage mitbeheben.
