### ISSUE TITLE
Etablierte Branch-Strategie

### ISSUE THREAD

**Issue by DataCerealz** [irgroup-classrooms/dis22-2022#16]
Für eine reibungslose Entwicklung sollte eine entsprechende Branching-Strategie vereinbart werden.

Folgender Vorschlag:
- Direktes pushen auf main und development wird technisch unterbunden (Umsetzung Rechtemanagement durch Admin @phschaer )
- Pull Requests dürfen erst nach erfolgreichen Workflowläufen gemerged werden
- Es sollte den main-Branch als "production"-Branch geben und einen "development" zur Entwicklung
- Für jeden Code der erstellt wird muss es mindestens ein Issue geben
- Für jedes Issue das geschlossen wird sollte es einen eigenen Feature-Branch geben
- Feature-Branches sollten spätestens am Ende von jedem Sprint auf Development gemerged werden
- development sollte bei Erreichen von Meilensteinen (neue Releaseversion, vgl. #7 , #8 ) auf main gemerged werden
- Hotfixes laufen über den gewohnten Workflow, aber außerhalb von Release-Zyklen (-> feature branch -> development -> main)

Das wäre eine sehr klassische aber einfache und effiziente Struktur.
Alternativen / Anmerkungen / Einspruch?

**Comment by DataCerealz** [comment]
Anlage: branches die erfolgreich gemerged wurden sollten sofort gelöscht werden.
Hinweis: ich habe branch protection schon einmal auf main und development gelegt um versehentliches Löschen durch jeden (Administratoren eingeschlossen) zu vermeiden. 
Ein Push auf development benötigt mindestens eine weitere Person die den Code gesehen hat und approved. Ein Push auf main 2 Personen. Die Zahl auf main könnten wir ggf. sogar noch erhöhen; aber so sollten wir bei Bedarf eilige und fehlerhafte Pushes schon einmal verhindern und auch wenn die Zeit dafür eigentlich nicht da ist...vielleicht kommen wir ja sogar in einen gesunden Code Review Rhythmus ;)

**Comment by okubon** [comment]
Deinen Vorschlag finde ich gut. Sollten wir so machen. 
Wie du bereits in der Whatsapp Gruppe vorgeschlagen hast, müsssten wir dann erstmal den Branch "Test" auf dev mergen. 
Willst du das dann machen?

**Comment by DataCerealz** [comment]
@okubon Pull request steht. Bitte noch dein approval dazu dann mergen wir 👍🏻

**Comment by DataCerealz** [comment]
### Automatische Schließung

Wenn bis Ende der Woche kein Widerspruch kommt würde ich diese Infos entsprechend in Contributing übernehmen (vgl. #20 ) und den Prozess als akzeptiert und gegeben ansehen.
