### ISSUE TITLE
Originales RAI Repo forken

### ISSUE THREAD

**Issue by okubon** [irgroup-classrooms/dis22-2022#2]
Hallo Herr Schaer,
wir möchten gerne das originalen  RAI Repo (https://github.com/gitronald/suggests) forken. Man muss es ja aber in eine Organisation forken. 
Wäre es vielleicht besser, wenn Sie dieses Repo in ihre Oraganisation forken oder sollen wir es irgendwo tun?

**Comment by phschaer** [comment]
Lieber Herr Kubon,

sorry, Ihre Anfrage blieb über Ostern einfach liegen bei mir. Sie können gerne das Repo "irgendwo" hin forken. Es muss nicht zwangsläufig diese Organisation sein. Wir können aber auch gerne zu einem späteren Zeitpunkt Ihren Fork in unserer Organisation überführen.

Für jetzt soll das aber erstmal kein Problem sein.

Alles Gute

Philipp Schaer

**Comment by okubon** [comment]
Fork wurde erstellt unter:
https://github.com/okubon/suggests

**Comment by okubon** [comment]
@phschaer ein Problem ist das nicht. Wie können wir uns denn am klügsten mit den von Ihnen angelegten Projekten arbeiten? Wenn wir Issues erstellen, dann haben wir in diesem Repo keinen Bezug zur Codebase im Fork. Wenn wir unsere Issues im Fork erstellen, dann bekommen Sie und der Rest nichts davon mit :/ 
Ich hoffe es ist veständlich was ich damit meine.

**Comment by phschaer** [comment]
Hmm... Das schauen wir uns wahrscheinlich morgen vor Ort an. Besser als über lange Mails.

**Comment by okubon** [comment]
Originale codebase des rai repos habe ich diesem repo hinzugefügt.
