### ISSUE TITLE
Export als Pickle oder Json Datei

### ISSUE THREAD

**Issue by Vetterino** [irgroup-classrooms/dis22-2022#48]
Hallo zusammen,

Der Umgang mit der Exportdatei als CSV stellt sich als etwas schwierig heraus.
Könnt ihr die Datei in einem anderen Format bereit stellen? Vorzugweise als Pickle, Json wäre auch eine Verbesserung.
Besten Dank im Voraus.

**Comment by DatenkrakeWasTaken** [comment]
Exports im pickle und json Format sind derzeit unter "dis22-2022/rai_app/export_file/" im Branch "48-export-als-pickle-oder-json-datei" verfügbar. Zu einem späteren Zeitpunkt werden diese auch im "development" Branch verfügbar sein.

**Comment by Vetterino** [comment]
Besten Dank!
