### ISSUE TITLE
Wie arbeitet man mit Issues in Github?

### ISSUE THREAD

**Issue by okubon** [irgroup-classrooms/dis22-2022#5]
Wir würden uns gerne in unserem Projekt bei Team 1 besser verwalten. Die Cards in solchen Projekte haben aber kaum eine Funktion und sind im Grunde einfach nur Notizzettel. Wenn man diese Cards aber in Issues umwandelt, dann hat man viel mehr Möglichkeiten wie  z.B. Zuweisung von Usern und Projekten. 

Issues klingen allerdings eher nach "Ich habe hier ein Problem und brauche Hilfe". 

Macht es also Sinn unsere To-Dos in Issues umzuwandeln?

**Comment by julesellaboranto** [comment]
Wir haben in unserem Repo nach der Logik gearbeitet, d.h. Issues angelegt und diese dann ins Board gezogen. So kann sich jede Person ein entsprechendes Ticket assignen und Unteraufgaben bearbeiten und abhaken.

**Comment by okubon** [comment]
Danke für die Antwort. 
Ich schließe das Ticket, da Paul schon einige Issues geöffnet hat und aller dadurch klarar wird.
