### ISSUE TITLE
Datensatz für Evaluation

### ISSUE THREAD

**Issue by Vetterino** [irgroup-classrooms/dis22-2022#58]
Hallo zusammen,

um das Matching zwischen der Ausgabedatei von Team 1 mit der Personenliste von Team 2 vorzunehmen benötigen wir einen eindeutigen Kenner. Hierfür bietet sich die UID aus der Personenliste an. Diese müsste noch mit aufgenommen werden.

Wann können wir mit dem finalen Export mit den vorausgewählten 1000 Personen rechnen? Ist diese Anzahl an Personen realistisch in dem Tool abzubilden und in welcher Tiefe plant ihr aktuell?

Schöne Grüße und Fragen jederzeit gerne.
Lucas

**Comment by ghost** [comment]
Hallo Lucas, 

die UID steht Euch doch zur Verfügung? Bezüglich der Auswahl: Tina müsste Euch eigentlich die Liste mit den 1.000 meistabgefragten Personen zur Verfügung gestellt haben, ansonsten könnt Ihr die aus der Gesamtliste mit Klickzahlen auch leicht herausfiltern.

Beste Grüße
Helga

**Comment by Vetterino** [comment]
Hi Helga,

Wir haben die Liste mit 330.000 Einträgen erhalten mit den Klickzahlen. Euer Vorschlag ist nach den Klickzahlen Top 1000 zu gehen? Ist das nach eurer Einschätzung repräsentativ? Dann kann Gruppe 1 ja hiermit die Daten erheben.

 Genau, in eurer Datei ist die UID enthalten, aber nicht in dem Output von Gruppe 1. Beispiel: Thomas Müller kommt mehrfach vor und wir können die beiden Dateien nicht eindeutig zusammenführen.

Schöne Grüße
Lucas

**Comment by ghost** [comment]
Hallo Lucas,

das angehängte Bild zeigt die ersten Dutzend - denke, das gibt schon ein ziemlich gutes Bild ab, was die (deutschsprachige) Welt bewegt hat in den letzten 12 Monaten.

![top_clicks_wiki](https://user-images.githubusercontent.com/63121391/177747550-ddbaafde-1982-4d43-9983-80cebb873f75.jpeg)
 
VG
Helga

**Comment by tpuddu** [comment]
Hallo Lucas,

die 1.000 waren ja nur eine Notlösung. Da wir jetzt doch die Klickzahlen von allen 330.000 Personen der letzten 12 Monate erhalten konnten, könnt ihr euch die Listen je nach euren geplanten Auswertungen selbst zusammen stellen.

VG Tina

**Comment by DatenkrakeWasTaken** [comment]
Hallo Lucas,

Soll die UID unique für jede Zeile sein, oder für jeden root?

**Comment by Vetterino** [comment]
Hey Datenkrake,

am besten als separate Spalte, damit wir die Zuordnung root -> UID erhalten. Dann ist das Zusammenfügen der Metadaten mit der Auswertung am einfachsten. Könnt ihr dann einen Durchlauf von Tinas Notlösung bereit stellen?

**Comment by DatenkrakeWasTaken** [comment]
Mit 1000 root nodes und einer Tiefe von 1 würde alleine der sleep timer, dessen Durchschnitt auf eine Sekunde gesetzt ist, summiert etwa acht Tage einnehmen.
@HaakFab Beim letzten Meeting hatten Sie eine potentielle Möglichkeit erwähnt das Skript auf einem Server remote ausführen zu können. Welche Schritte müssten eingeleitet werden um Zugriff auf den Server zu bekommen?

**Comment by HaakFab** [comment]
@DatenkrakeWasTaken Ich organisiere das und lasse Ihnen heute oder morgen strukturierte Infos dazu zukommen! 
VG

**Comment by DataCerealz** [comment]
Google mag das nicht besonders, entsprechend der sleep timer. Gruppe 3 wird entweder einen rotating proxy oder eine Lizenz für ein SERP Tool brauchen wenn sie wirklich große Mengen an Daten mit dem Tool erheben wollen. (Wenn dem so ist. Bin in der RAI Gruppe und wir haben ja nur das Tool gebaut - was Gruppe 3 wie an Daten verarbeiten will oder braucht wissen wir nicht). Nach meinem letzten Stand ist das crawlen ohnehin gegen Google TOS falls sich das in letzter Zeit nicht geändert hat; entsprechend wäre SERP dem rotating proxy vorzuziehen um die Verantwortung umzuverlagern...aber ich gehe einfach mal davon aus rechtliche Aspekte wurden vor der Aufgabenstellung in Betracht gezogen und ein rotating proxy wäre als günstige Alternative für Gruppe 3 auch valide, oder @HaakFab , @phschaer ?

**Comment by HaakFab** [comment]
@DataCerealz Das ist richtig, Google sieht es eigentlich nicht vor, größere Crawls durchzuführen. Daher bleibt, wie Sie sagten, Proxies oder spezielle Tools zu verwenden. Natürlich ist man damit immer noch nicht aus dem Schneider, für wissenschaftliche Zwecke rechtfertigt hier der Zweck aber mMn die Mittel- und Proxies sind da wahrscheinlich die einfachste Lösung. Sollte es damit Probleme geben, können wir aber immer noch auf eine (teurere) Lösung umschwenken. 
VG

**Comment by Vetterino** [comment]
@DataCerealz Wir (Gruppe 3) stellen keine Ansprüche bzgl. Größe, oder tiefe der Abfrage. Hier verlassen wir uns auf eure Einschätzung was realistisch in der Umsetzung ist. Im letzten Sprint haben wir offen darüber diskutiert und uns wurde die Anzahl 1000 avisiert. Wenn das nicht realistisch ist, sollten wir das anpassen. Wie besprochen haben wir unsere Hypothese online gestellt, damit wir gemeinsam auf das selbe Ziel hinarbeiten. Wir folgen der Empfehlung von Gruppe 2 und nehmen zunächst eine Auswahl nach Klickzahlen. Wenn es hier noch eurerseits offene Fragen gibt, sollten wir diese Morgen klären.
Schöne Grüße
Lucas

**Comment by DataCerealz** [comment]
> @DataCerealz Wir (Gruppe 3) stellen keine Ansprüche bzgl. Größe, oder tiefe der Abfrage. Hier verlassen wir uns auf eure Einschätzung was realistisch in der Umsetzung ist.
> 

Alles. Ihr macht die Auswertung, entsprechend werdet auch nur ihr entscheiden können welche Datenqualität, Umfang, und Tiefe ihr braucht um eure Aussagen treffen zu können. Das Tool ist aktuell in der Geschwindigkeit limitiert, allerdings ist das ja kein Hindernis; hier gibt es viele Wege vorbei. Wenn ihr sagt ihr braucht nur von den Top 3 Personen nach Klicks mit Tiefe 1 Daten dann könnt ihr es einfach runterladen und starten; kein Thema. Wenn ihr sehr viel mehr braucht müsstet ihr euch einen rotating proxy oder SERP tool besorgen. Wenn es hierfür kein Budget gibt, macht sich jeder ein AWS Student Konto und hängt sich 10 EC2-Maschinen auf (kurzes Tutorial ist auf der Startseite von AWS Educate). Dauert keine volle Stunde und wenn das nur 3 Personen machen habt ihr schon 30 Maschinen die parallel laufen; dann sind auch größere Datenmengen in 24h durch. Wie viel ihr braucht für das was ihr feststellen wollt und wie viel euch reicht um zu entscheiden dass eine qualitative Aussage getroffen werden kann können wir, die nur das Tool bereitstellen, nicht bewerten. Wenn ihr eure Anforderungen habt und feststellt dass der absolut einzige Weg diese umzusetzen Anpassungen am Tool erfordert dann haben wir erst wieder ein Thema; aber das Tool benutzen wie ihr es braucht müsst ihr schon selber. Deshalb war unsere Aufgabe auch ein Tool zu bauen - keine Lösung. Würde ja auch keinen Sinn machen wenn Leute random Daten beschaffen die andere auswerten müssen ohne im Auswertungsprozess zu hängen.

Aufgabe 3 war Analyse hinsichtlich topical bias. Wie und mit welchen Daten ihr das umsetzen wollt wissen wir nicht. Wenn ihr nur auf Politiker wollt und das Gruppe 2 Set nach Politiker filtert und dann vllt nur aktuell regierende Politiker wollt mit Tiefe 1: dann reicht das Tool wohl um es mal eben lokal laufen zu lassen. Wenn ihr irgendein Gender Thema wollt in allem was mit Kunst zutun hat auf den 330.000 Datensätzen von Gruppe 2: dann wird das wohl nichts und ihr müsst Proxy/SERP/oder meine spontane AWS-Idee oder eine andere eigene Lösung suchen.

Wenn ihr entscheidet dass es rotating proxy oder SERP werden soll - wie auch immer begründet - und den über Haak/Schaer besorgt dann können wir euch den gerne einbauen.
