### ISSUE TITLE
Finaler Datensatz generieren

### ISSUE THREAD

**Issue by PascalPelzers** [irgroup-classrooms/dis22-2022#67]
Hey

Wir haben nun eine finale Auswahl an Personen erstellt, falls noch jemand aus der 2ten Gruppe Feedback hierzu hat gerne mit uns teilen. 
Ansonsten würde jetzt noch die Frage im Raum stehen, wer die Export-Datei erstellt. 
Soweit ich das verstanden habe, macht das noch Gruppe 1, richtig?  
Wäre dann super, wenn ihr Bescheid gebt, sobald die Datei für uns zur Analyse vorhanden ist.

Danke und noch eine schöne Woche :)

**Comment by auringonnousu** [comment]
Hallo, Gibt es hierzu ein Update?

**Comment by DatenkrakeWasTaken** [comment]
Wo genau liegt die finale Importdatei?
Ich kann die im Repository nicht finden.

**Comment by Vetterino** [comment]
Der liegt im Branch Vetterino - patch 1 im Ordner Analysis ([WikiPersonen_final_60.xlsx](https://github.com/irgroup-classrooms/dis22-2022/blob/Vetterino-patch-1/Analysis/WikiPersonen_final_60.xlsx)

**Comment by DatenkrakeWasTaken** [comment]
Kurzer Zwischenstand: UID ist im Skript integriert und der Code wird aktuell auf dem Server ausgeführt.

**Comment by Vetterino** [comment]
Super, besten Dank! Kannst du absehen, wann der Lauf fertig ist?

**Comment by DatenkrakeWasTaken** [comment]
Wenn keine Fehler auftreten und es in der Geschwindigkeit weiterläuft, müsste der Lauf in drei Tagen durch sein.
Bei meiner Berechnung der Dauer des sleep timers in Kombination mit der alphabetischen Erweiterung ist mir letztes Mal leider ein Fehler unterlaufen, wodurch ich die Dauer noch unterschätzt hatte. Deshalb dauert es trotz der Reduktion auf 60 Personen leider einige Tage.

**Comment by DatenkrakeWasTaken** [comment]
So, das Skript ist durchgelaufen. Wegen der Dateigröße lade ich die exports nicht hier in GitHub hoch.
Ich hab die exportierten files in sciebo hochgeladen: https://th-koeln.sciebo.de/s/wlB6ltpY07G3dwY
Alle export.xyz Dateien sind unverändert, bei export_no_duplicates.pickle wurden Duplikate der "target" Spalte entfernt.

**Comment by Vetterino** [comment]
Besten Dank!
